/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Passenger;
import bean.Ticket;
import controller.ControllerFlightSchedule;
import controller.ControllerPassenger;
import controller.ControllerSeatNo;
import controller.ControllerTicket;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import library.ConvertDate;

/**
 *
 * @author DELL
 */
public class AddPassenger extends javax.swing.JFrame {
    private ConvertDate convertDate;
    private ControllerFlightSchedule controllerFlightSchedule;
    private ControllerPassenger controllerPassenger;
    private ControllerTicket controllerTicket;
    private ControllerSeatNo controllerSeatNo;
    private Passenger objPassenger;
    private int idFlightSchedule1 = 0;
    private int idSeatNo1 = 0;
    

    /**
     * Creates new form AddPassenger
     */
    public AddPassenger(int idFlightSchedule, int idSeatNo) {
        initComponents();
        this.setLocationRelativeTo(null);
        idFlightSchedule1 = idFlightSchedule;
        idSeatNo1 = idSeatNo;
        controllerPassenger = new ControllerPassenger(null);
        controllerTicket = new ControllerTicket(null);
        controllerSeatNo = new ControllerSeatNo();
        convertDate = new ConvertDate();
        jRadioButtonMale.setActionCommand("Male");
        jRadioButtonFemale.setActionCommand("Female");
        controllerFlightSchedule = new ControllerFlightSchedule(null);
        jButtonSearch.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSubmit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPassport = new javax.swing.JTextField();
        jTextFieldFullName = new javax.swing.JTextField();
        datePickerBirthday = new com.github.lgooddatepicker.components.DatePicker();
        jTextFieldNative = new javax.swing.JTextField();
        jTextFieldNationality = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jButtonNext = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Create Passenger");
        jPanel1.add(jLabel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButtonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSubmit);

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Passport:");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setText("Full name:");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setText("Birthday:");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setText("Native:");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setText("Gender:");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setText("Nationality:");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setText("Address:");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setText("Phone:");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldPassport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPassportMouseClicked(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        buttonGroupGender.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButtonNext.setText("Next ->");
        jButtonNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        jButtonSearch.setText("search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNationality, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNative, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldFullName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datePickerBirthday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButtonMale)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonFemale)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldPassport)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(datePickerBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonMale)
                    .addComponent(jRadioButtonFemale))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        AddPassenger.this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
       String passport = jTextFieldPassport.getText();
        String fullName = jTextFieldFullName.getText();
        if(datePickerBirthday.getDateStringOrEmptyString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter Birthday ");
            return;
        }
        java.sql.Date sqlBirthday = new java.sql.Date(convertDate.getDateTime(datePickerBirthday.getDateStringOrEmptyString()).getTime());
        String nativeCountry = jTextFieldNative.getText();
         if(buttonGroupGender.getSelection()==null){
            JOptionPane.showMessageDialog(null, "Please enter Gender ");
            return;
        }
        String gender = buttonGroupGender.getSelection().getActionCommand();
        String nationality = jTextFieldNationality.getText();
        String phone = jTextFieldPhone.getText();
        String address = jTextFieldAddress.getText();
        if((idFlightSchedule1 != 0) && (idSeatNo1 != 0) && (objPassenger != null)){
            Ticket objTicket = new Ticket(0, objPassenger.getId(), idFlightSchedule1, idSeatNo1);
            int result = controllerTicket.addTicket(objTicket);
            if(result > 0){
                int updateSeatNo = controllerSeatNo.updateSeatNo(idSeatNo1);
                if(updateSeatNo > 0){
                    JOptionPane.showMessageDialog(null, "Order successfully!");
                    AddPassenger.this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Error when order seat no. Please try again!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Error when order ticket. Please try again!");
            }
        }else{
            Passenger objPassenger = new Passenger(0, passport, fullName, sqlBirthday, nativeCountry, gender, nationality, phone, address);
			if (!isValid( objPassenger)) {
            return;
			}
        
            int idPassenger = controllerPassenger.addPassenger(objPassenger);
            if((idPassenger > 0) && (idFlightSchedule1 != 0) && (idSeatNo1 != 0)){
                Ticket objTicket = new Ticket(0, idPassenger, idFlightSchedule1, idSeatNo1);
                int result = controllerTicket.addTicket(objTicket);
                if(result > 0){
                    int updateSeatNo = controllerSeatNo.updateSeatNo(idSeatNo1);
                    if(updateSeatNo > 0){
                        JOptionPane.showMessageDialog(null, "Order successfully!");
                        AddPassenger.this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Error when order seat no. Please try again!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Error when order ticket. Please try again!");
                }
            }
            if(idPassenger < 0){
                JOptionPane.showMessageDialog(null, "Error when create passenger. Please try again!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Create passenger successfully!");
                AddPassenger.this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        jButtonSearch.setEnabled(true);
        jTextFieldPassport.setText("Enter your passport...");
        jButtonNext.setEnabled(false);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String passport = jTextFieldPassport.getText();
        objPassenger = controllerPassenger.findPassenger(passport);
        if(objPassenger != null){
            JOptionPane.showMessageDialog(null, "Found successfully!");
            setForm(objPassenger);
        }else{
            JOptionPane.showMessageDialog(null, "Not found!!");
        }
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldPassportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPassportMouseClicked
        // TODO add your handling code here:
        jTextFieldPassport.setText("");
    }//GEN-LAST:event_jTextFieldPassportMouseClicked
    
    public void setForm(Passenger objPassenger){
        jTextFieldPassport.setText(objPassenger.getPassport());
        jTextFieldFullName.setText(objPassenger.getFullName());
        java.sql.Date sqlDate = new java.sql.Date(objPassenger.getBirthday().getTime());
        LocalDate localBirthday = sqlDate.toLocalDate();
        datePickerBirthday.setDate(localBirthday);
        jTextFieldNative.setText(objPassenger.getNativeCountry());
        jTextFieldNationality.setText(objPassenger.getNativeCountry());
        jTextFieldPhone.setText(objPassenger.getPhone());
        jTextFieldAddress.setText(objPassenger.getAddress());
        if(objPassenger.getGender().equals("Male")){
            jRadioButtonMale.setSelected(true);
        }else{
            jRadioButtonFemale.setSelected(true);
        }
    }
    private boolean isValid(Passenger objItem) {
        if (objItem.getPassport().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter  Passport");
            return false;
        }
         if (!objItem.getPassport().matches("[0-9]+")) {
             JOptionPane.showMessageDialog(this, "Please enter a valid Passport format");
            return false;
        }
        if (objItem.getFullName().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter  fullname");
            return false;
        }
       if (objItem.getNativeCountry().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter NativeCountry");
            return false;
        }
        if (objItem.getNationality().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Nationality");
            return false;
        }
        if (objItem.getPhone().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Phone");
            return false;
        }
         if (!objItem.getPhone().matches("[0-9]+")) {
             JOptionPane.showMessageDialog(this, "Please enter a valid Phone format");
            return false;
        }
        if (objItem.getAddress().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Address");
            return false;
        }
        
       return  true;

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPassenger(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGender;
    private com.github.lgooddatepicker.components.DatePicker datePickerBirthday;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldFullName;
    private javax.swing.JTextField jTextFieldNationality;
    private javax.swing.JTextField jTextFieldNative;
    private javax.swing.JTextField jTextFieldPassport;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
