/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.SeatNo;
import controller.ControllerSeatNo;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author DELL
 */
public class ChooseSeatNo extends javax.swing.JFrame {
    private ControllerSeatNo controllerSeatNo;
    private javax.swing.JPanel pnSeatNo;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton btSeatNo;
    private ArrayList<SeatNo> alSeatNo;
    private SeatNo objSeatNo;
    private int idFlightSchedule1;

    /**
     * Creates new form SeatNo
     */
    public ChooseSeatNo(int idFlightSchedule) {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        idFlightSchedule1 = idFlightSchedule;
        controllerSeatNo = new ControllerSeatNo();
        alSeatNo = controllerSeatNo.getList(idFlightSchedule);
        pnSeatNo = new JPanel();
        for(int x = 0; x < alSeatNo.size(); x ++){
            objSeatNo = alSeatNo.get(x);
            btSeatNo = new JButton(objSeatNo.getName());
            btSeatNo.setActionCommand(Integer.toString(alSeatNo.get(x).getId()));
            pnSeatNo.add(btSeatNo);
            if(objSeatNo.isStatus() == true){
                btSeatNo.setBackground(Color.YELLOW);
                this.btSeatNo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        JOptionPane.showMessageDialog(null, "You can not choose this seat no!");
                    }
                });
            }else{
                this.btSeatNo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btRegisterActionPerformed(((JButton) evt.getSource()).getActionCommand());
                    }
                });
            }
            btSeatNo.setPreferredSize(new Dimension(50, 53));
        }
        scrollPane = new JScrollPane(pnSeatNo);
        pnSeatNo.setLayout(new java.awt.GridLayout(0, 10));
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        pnCenter.add(scrollPane);
        pnCenter.validate();
        pnCenter.repaint();
    }
    private void btRegisterActionPerformed(String idSeatNo) {
        int idIntegerSeatNo = Integer.parseInt(idSeatNo);
        new AddPassenger(idFlightSchedule1, idIntegerSeatNo).setVisible(true);
        ChooseSeatNo.this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnCenter.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Register seat No");
        jPanel1.add(jLabel2);

        pnCenter.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        pnCenter.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ChooseSeatNo.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSeatNo(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnCenter;
    // End of variables declaration//GEN-END:variables
}
