/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Ticket;
import bean.SeatNo;
import controller.ControllerSeatNo;
import controller.ControllerTicket;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author DELL
 */
public class EditSeatNo extends javax.swing.JFrame {
    private ControllerTicket controllerTicket;
    private ControllerSeatNo controllerSeatNo;
    private javax.swing.JPanel pnSeatNo;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton btSeatNo;
    private ArrayList<SeatNo> alSeatNo;
    private Ticket objTicket;
    private SeatNo objSeatNo;
    private int idFlightSchedule1;

    /**
     * Creates new form SeatNo
     */
    public EditSeatNo(Ticket item) {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        idFlightSchedule1 = item.getIdFlightSchedule();
        controllerSeatNo = new ControllerSeatNo();
        controllerTicket = new ControllerTicket(null);
        objTicket = item;
        alSeatNo = controllerSeatNo.getList(item.getIdFlightSchedule());
        pnSeatNo = new JPanel();
        for(int x = 0; x < alSeatNo.size(); x ++){
            objSeatNo = alSeatNo.get(x);
            btSeatNo = new JButton(objSeatNo.getName());
            btSeatNo.setActionCommand(Integer.toString(alSeatNo.get(x).getId()));
            pnSeatNo.add(btSeatNo);
            if(objSeatNo.isStatus() == true){
                btSeatNo.setBackground(Color.YELLOW);
                this.btSeatNo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        JOptionPane.showMessageDialog(null, "You can not edit!");
                    }
                });
            }else{
                this.btSeatNo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btEditActionPerformed(((JButton) evt.getSource()).getActionCommand());
                    }
                });
            }
            btSeatNo.setPreferredSize(new Dimension(50, 53));
        }
        scrollPane = new JScrollPane(pnSeatNo);
        pnSeatNo.setLayout(new java.awt.GridLayout(0, 10));
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        pnCenter.add(scrollPane);
        pnCenter.validate();
        pnCenter.repaint();
    }
    private void btEditActionPerformed(String idSeatNo) {
        int idIntegerSeatNo = Integer.parseInt(idSeatNo);
        int result = JOptionPane.showConfirmDialog(null, 
            "Do you want to edit?",null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            // Delet seatNo
            int editSeatNo = controllerTicket.editSeatNo(objTicket.getId() , idIntegerSeatNo);
            if(editSeatNo > 0){
                int removeSeatNo = controllerSeatNo.removeSeatNo(objTicket.getIdSeatNo());
                if(removeSeatNo > 0){
                    int updateSeatNo = controllerSeatNo.updateSeatNo(idIntegerSeatNo);
                    if(updateSeatNo > 0){
                        JOptionPane.showMessageDialog(null, "Successfully updateSeatNo!");
                        EditSeatNo.this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Error updateSeatNo!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Error removeSeatNo!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Error editSeatNo!");
            }
            EditSeatNo.this.dispose();
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelHeader.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List seat No");
        jPanelHeader.add(jLabel1);

        getContentPane().add(jPanelHeader, java.awt.BorderLayout.PAGE_START);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButton1);

        getContentPane().add(jPanelFooter, java.awt.BorderLayout.PAGE_END);

        pnCenter.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EditSeatNo.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSeatNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSeatNo(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel pnCenter;
    // End of variables declaration//GEN-END:variables
}
