/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import bean.Airplane;
import bean.FlightSchedule;
import controller.ControllerAirplane;
import controller.ControllerFlightSchedule;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class FlightScheduleManagement extends javax.swing.JPanel {
    private ControllerFlightSchedule controllerFlightSchedule;
    private ControllerAirplane controllerAirplane;
    private int row;
    /**
     * Creates new form FlightScheduleManagement
     */
    public FlightScheduleManagement() {
        initComponents();
        controllerFlightSchedule = new ControllerFlightSchedule(tbMain);
        controllerAirplane = new ControllerAirplane(null);
        controllerAirplane.loadAirplane(jComboBoxAirplane, true, null);
        controllerFlightSchedule.loadTable();
        this.loadActionListener();
    }
    private void findAirplane(String name) {
        TableRowSorter sorter = new TableRowSorter(tbMain.getModel());
        tbMain.setRowSorter(sorter);
        RowFilter<AbstractTableModel, Object> filterAirplane = RowFilter.regexFilter(name, 4);
        ArrayList<RowFilter<AbstractTableModel, Object>> arList = new ArrayList<>();
        arList.add(filterAirplane);
        RowFilter<AbstractTableModel, Object> find = RowFilter.andFilter(arList);
        sorter.setRowFilter(find);
    }
    
    public void loadActionListener(){
        ((JLabel)jComboBoxAirplane.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        jComboBoxAirplane.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                Airplane objAirplane = (Airplane)jComboBoxAirplane.getSelectedItem();
                if(objAirplane.getId() != 0){
                    findAirplane(objAirplane.getName());
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFunction = new javax.swing.JPanel();
        jPanelCRUD = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDetail = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jPanelSearch = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jComboBoxAirplane = new javax.swing.JComboBox<>();
        jPanelDisplay = new javax.swing.JPanel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanelFunction.setLayout(new java.awt.BorderLayout());

        jPanelCRUD.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanelCRUD.add(jButtonAdd);

        jButtonEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanelCRUD.add(jButtonEdit);

        jButtonDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        jButtonDetail.setText("Detail");
        jButtonDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailActionPerformed(evt);
            }
        });
        jPanelCRUD.add(jButtonDetail);

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.gif"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelCRUD.add(jButtonDelete);

        jPanelFunction.add(jPanelCRUD, java.awt.BorderLayout.PAGE_START);

        jTextFieldSearch.setText("Enter name flight schedule...");
        jTextFieldSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSearchMouseClicked(evt);
            }
        });

        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jComboBoxAirplane.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxAirplane.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----- Choose flight schedule -----", "Day", "Week", "Month", "Year" }));
        jComboBoxAirplane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jComboBoxAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch)
                .addContainerGap())
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAirplane, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jTextFieldSearch)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelFunction.add(jPanelSearch, java.awt.BorderLayout.PAGE_END);

        add(jPanelFunction, java.awt.BorderLayout.PAGE_START);

        jPanelDisplay.setLayout(new java.awt.BorderLayout());

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbMain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMainMousePressed(evt);
            }
        });
        jScrollPaneTable.setViewportView(tbMain);

        jPanelDisplay.add(jScrollPaneTable, java.awt.BorderLayout.CENTER);

        add(jPanelDisplay, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        new RegisterFilghtSchedule().setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void tbMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainMousePressed
        // TODO add your handling code here:
        row = tbMain.getSelectedRow();
        FlightSchedule item = controllerFlightSchedule.getValueAtRows(row);
        tbMain.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) 
            {
                int r = tbMain.rowAtPoint(e.getPoint());
                if (r >= 0 && r < tbMain.getRowCount()) {
                tbMain.setRowSelectionInterval(r, r);
            } else {
                tbMain.clearSelection();
            }
            if (e.isPopupTrigger() && e.getComponent() instanceof JTable ) {
                JPopupMenu popup = createYourPopUp(item,tbMain);
                popup.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }//GEN-LAST:event_tbMainMousePressed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        row = tbMain.getSelectedRow();
        if(row >= 0){
            FlightSchedule item = controllerFlightSchedule.getValueAtRows(row);
            if(item.isStatus()){
                JOptionPane.showMessageDialog(null, "You can not edit this flight schedule!");
            }else{
                new EditFlightSchedule(item).setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please choose a flight schedule!");

        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        row = tbMain.getSelectedRow();
        
        if(row >= 0){
            FlightSchedule item = controllerFlightSchedule.getValueAtRows(row);
            int result = JOptionPane.showConfirmDialog(null, "Are you sure?",null, JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION) {
                int resultDelete = controllerFlightSchedule.deleteFlightSchedule(item.getId(), row);
                if(resultDelete > 0){
                    JOptionPane.showMessageDialog(null, "Delete successfully!");
                }else{
                    JOptionPane.showMessageDialog(null, "Delete error!");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please choose a flight schedule!");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchMouseClicked
        // TODO add your handling code here:
        jTextFieldSearch.setText("");
    }//GEN-LAST:event_jTextFieldSearchMouseClicked

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        TableRowSorter sorter = new TableRowSorter(tbMain.getModel());
        tbMain.setRowSorter(sorter);
        String nameFlightSchedule = jTextFieldSearch.getText();
        RowFilter<AbstractTableModel, Object> filterNameFlightSchedule = RowFilter.regexFilter("(?i)" + nameFlightSchedule, 1);
        ArrayList<RowFilter<AbstractTableModel, Object>> arList = new ArrayList<>();
        arList.add(filterNameFlightSchedule);
        RowFilter<AbstractTableModel, Object> find = RowFilter.andFilter(arList);
        sorter.setRowFilter(find);
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailActionPerformed
        // TODO add your handling code here:
        row = tbMain.getSelectedRow();
        if(row >= 0){
            FlightSchedule item = controllerFlightSchedule.getValueAtRows(row);
            new DetailFlightSchedule(item).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Choose a flight schedule");
        }
    }//GEN-LAST:event_jButtonDetailActionPerformed
    
    public JPopupMenu createYourPopUp(FlightSchedule item, JTable table)
    {
        JPopupMenu popup=new JPopupMenu();
        JMenuItem register =new JMenuItem("Register");
        JMenuItem done =new JMenuItem("Done");  
        JMenuItem edit = new JMenuItem("Edit");
        JMenuItem detail =new JMenuItem("Detail");
        JMenuItem delete =new JMenuItem("Delete");
        register.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new ChooseSeatNo(item.getId()).setVisible(true);
            }
        });
        done.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int result = controllerFlightSchedule.doneFlightSchedule(item, table.getSelectedRow());
                if(result > 0){
                    item.setStatus(true);
                    JOptionPane.showMessageDialog(null, "Done");
                }else{
                    JOptionPane.showMessageDialog(null, "Fail. Please try again!");
                }
            }
        });
        edit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new EditFlightSchedule(item).setVisible(true);
            }
        });
        detail.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new DetailFlightSchedule(item).setVisible(true);
            }
        });
        delete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int result = JOptionPane.showConfirmDialog(null, 
                    "Are you sure?",null, JOptionPane.YES_NO_OPTION);
                if(result == JOptionPane.YES_OPTION) {
                    int resultDelete = controllerFlightSchedule.deleteFlightSchedule(item.getId(), row);
                    if(resultDelete > 0){
                        JOptionPane.showMessageDialog(null, "Delete successfully!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Delete error!");
                    }
                }
            }
        });
        if(item.isStatus() != true){
            popup.add(register);
            popup.add(done);
            popup.add(edit);
        }
        popup.add(detail);
        popup.add(delete);
        return popup;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDetail;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxAirplane;
    private javax.swing.JPanel jPanelCRUD;
    private javax.swing.JPanel jPanelDisplay;
    private javax.swing.JPanel jPanelFunction;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTable tbMain;
    // End of variables declaration//GEN-END:variables
}
