/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.User;
import controller.ControllerUser;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import library.LibraryString;
import library.RememberMe;

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JFrame {
    private LibraryString libraryString;
    private ControllerUser controllerUser;
    private RememberMe rememberMe;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        libraryString = new LibraryString();
        controllerUser = new ControllerUser(0);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        pnMain.setMaximumSize(new Dimension(579, 400));
        pnMain.setMinimumSize(new Dimension(579, 400));
        btLogin.setOpaque(false);
        btLogin.setContentAreaFilled(false);
        tfUsername.setBackground(new Color(0, 0, 0, 0));
        tfUsername.setBorder(BorderFactory.createEmptyBorder());
        tfPassword.setBackground(new Color(0, 0, 0, 0));
        tfPassword.setBorder(BorderFactory.createEmptyBorder());
        rememberMe = new RememberMe();
        rememberMe.UPDATE(tfUsername, tfPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRememberMe = new javax.swing.ButtonGroup();
        pnMain = new javax.swing.JPanel();
        cbRememberMe = new javax.swing.JCheckBox();
        cbForgetMe = new javax.swing.JCheckBox();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupRememberMe.add(cbRememberMe);
        cbRememberMe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbRememberMe.setForeground(new java.awt.Color(0, 102, 153));
        cbRememberMe.setText("Remember me");
        cbRememberMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRememberMeActionPerformed(evt);
            }
        });

        buttonGroupRememberMe.add(cbForgetMe);
        cbForgetMe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbForgetMe.setForeground(new java.awt.Color(0, 102, 255));
        cbForgetMe.setText("Forget");
        cbForgetMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbForgetMeActionPerformed(evt);
            }
        });

        tfUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        tfPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frlogin.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(cbRememberMe))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(cbForgetMe))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(cbRememberMe))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(cbForgetMe))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRememberMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRememberMeActionPerformed
        // TODO add your handling code here:
        if(cbRememberMe.isSelected()){
            rememberMe.SAVE(tfUsername, tfPassword);
        }
    }//GEN-LAST:event_cbRememberMeActionPerformed

    private void cbForgetMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbForgetMeActionPerformed
        // TODO add your handling code here:
        if(cbForgetMe.isSelected()){
            rememberMe.FORGET();
        }
    }//GEN-LAST:event_cbForgetMeActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        String username = tfUsername.getText();
        String password = tfPassword.getText();
        String passMD5 = libraryString.md5(password);
        User objUser = new User(username, passMD5);
        int idUser = controllerUser.checkUser(objUser);
        if(idUser > 0){
            Login.this.dispose();
            new Main(idUser).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Username or password are not defined!");
        }
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.ButtonGroup buttonGroupRememberMe;
    private javax.swing.JCheckBox cbForgetMe;
    private javax.swing.JCheckBox cbRememberMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
