/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Employee;
import controller.ControllerEmployee;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Main extends javax.swing.JFrame {
    private ControllerEmployee controllerEmployee;
    private Employee objEmployee;
    private int idEmployee;

    /**
     * Creates new form Main
     */
    public Main(int idUser) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        controllerEmployee = new ControllerEmployee(null);
        idEmployee = idUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        profile = new javax.swing.JPanel();
        jButtonProfile = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        listFunction = new javax.swing.JPanel();
        btPassenger = new javax.swing.JButton();
        btFlightSchedule = new javax.swing.JButton();
        btTicket = new javax.swing.JButton();
        btEmployee = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setLayout(new java.awt.BorderLayout());

        jButtonProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qluser.png"))); // NOI18N
        jButtonProfile.setText("Admin");
        jButtonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfileActionPerformed(evt);
            }
        });

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-logout.gif"))); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addContainerGap())
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProfile)
                    .addComponent(jButtonLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.add(profile, java.awt.BorderLayout.EAST);

        listFunction.setLayout(new java.awt.GridLayout(1, 0));

        btPassenger.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPassenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_passenger.png"))); // NOI18N
        btPassenger.setText("Passenger");
        btPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPassengerActionPerformed(evt);
            }
        });
        listFunction.add(btPassenger);

        btFlightSchedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btFlightSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_flight.png"))); // NOI18N
        btFlightSchedule.setText("Flight schedule");
        btFlightSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFlightScheduleActionPerformed(evt);
            }
        });
        listFunction.add(btFlightSchedule);

        btTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ticket.png"))); // NOI18N
        btTicket.setText("Ticket");
        btTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTicketActionPerformed(evt);
            }
        });
        listFunction.add(btTicket);

        btEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_employee.png"))); // NOI18N
        btEmployee.setText("Employee");
        btEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmployeeActionPerformed(evt);
            }
        });
        listFunction.add(btEmployee);

        header.add(listFunction, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        footer.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copy right 12T4");
        footer.add(jLabel1);

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        body.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N
        body.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Config Airplane");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPassengerActionPerformed
        // TODO add your handling code here:
        body.removeAll();
        body.add(new PassengerManagement(), BorderLayout.CENTER);
        body.revalidate();
    }//GEN-LAST:event_btPassengerActionPerformed

    private void btFlightScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFlightScheduleActionPerformed
        // TODO add your handling code here:
        body.removeAll();
        body.add(new FlightScheduleManagement(), BorderLayout.CENTER);
        body.revalidate();
    }//GEN-LAST:event_btFlightScheduleActionPerformed

    private void btTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTicketActionPerformed
        // TODO add your handling code here:
        body.removeAll();
        body.add(new TicketManagement(), BorderLayout.CENTER);
        body.revalidate();
    }//GEN-LAST:event_btTicketActionPerformed

    private void jButtonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfileActionPerformed
        // TODO add your handling code here:
        objEmployee = controllerEmployee.profile(idEmployee);
        if(objEmployee != null){
            new EditEmployee(objEmployee).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Please login!");
        }
    }//GEN-LAST:event_jButtonProfileActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, 
            "Are you sure you wish to logout?",null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            Main.this.dispose();
            new Login().setVisible(true);
        } 
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void btEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmployeeActionPerformed
        // TODO add your handling code here:
        body.removeAll();
        body.add(new EmployeeManagement(), BorderLayout.CENTER);
        body.revalidate();
    }//GEN-LAST:event_btEmployeeActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        body.removeAll();
        body.add(new AirplaneManagement(), BorderLayout.CENTER);
        body.revalidate();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btEmployee;
    private javax.swing.JButton btFlightSchedule;
    private javax.swing.JButton btPassenger;
    private javax.swing.JButton btTicket;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel listFunction;
    private javax.swing.JPanel profile;
    // End of variables declaration//GEN-END:variables
}
